config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root to: "blogs#index"
resources :users
resources :blogs do
  resources :favorites, only: [:create, :destroy, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :users, through: :favorites

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :blogs, through: :favorites
  has_many :favorites

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.includes(:user, :favorites).page(params[:page]).per(4).order("created_at DESC")
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(text: blog_params[:text],image: blog_params[:image], name: blog_params[:name],user_id: current_user.id)
    @blog.save
  end

  def destroy
    blog = Blog.find(params[:id])
    if blog.user_id == current_user.id
      blog.destroy
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    blog = Blog.find(params[:id])
    if blog.user_id == current_user.id
      blog.update(blog_params)
    end
  end


  def blog_params
    params.require(:blog).permit(:image, :text, :name)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = Favorite.create(user_id: current_user.id, blog_id: params[:blog_id])
    @favorites = Favorite.where(blog_id: params[:blog_id])
    @blogs = Blog.all
  end

  def destroy
    user = User.find(params[:id])
    @favorites = Favorite.where("user_id = ?", user)
    @favorites.each do |favorite|
    favorite.destroy
    end
  end

  def show
    user = User.find(params[:id])
    @favorites = Favorite.where("user_id = ?", user)
    @blogs = user.blogs.page(params[:page]).per(4).order("created_at DESC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
   @blogs = user.blogs.page(params[:page]).per(4).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_posted_time(time)
    fixed_time = time
    return fixed_time.strftime("%Y/%m/%d %H:%M")
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_content.html.haml
.contents
  .maincontent
    - @blogs.each do |blog|
      .maincontents
        .content__poems
          .content__poems-text
            .content__poems-text-box
              - if blog.text.present?
                = blog.text
              .content__poems-image-box
              = image_tag blog.image
                -if blog.image.present?
              .content__poems-name-box
              = blog.name
              .content__poems-time-box
              = format_posted_time(blog.created_at)
            %ul.content__lists
              -if user_signed_in? && current_user.id == blog.user_id
                %li.list
                  =link_to "編集ボタン", edit_blog_path(blog.id), method: :get
                %li.list
                  =link_to "削除ボタン", "/blogs/#{blog.id}", method: :delete, data: { confirm: 'Are you sure?' }
              -else
                %li.list
                  =link_to blog_favorites_path(blog.id), method: :post do
                    %i.large.material-icons favorite_border
                %li.list
                  =link_to "blogs/#{blog.id}/favorites/#{blog.user.id}", method: :delete do
                    %i.large.material-icons favorite
  = paginate @blogs

app/views/blogs/_header.html.haml
.header
  %h2.header__title
    = link_to root_path do
      Poemer
  - @blogs.each do |blog|
    %ul.header__lists
      - if user_signed_in?
        %li.list
          = link_to "投稿", new_blog_path, method: :get
        %li.list
          = link_to "マイページ", "users/#{blog.user.id}", method: :get
        %li.list
          = link_to "お気に入り一覧", "blogs/#{blog.id}/favorites/#{blog.user.id}", method: :get
        %li.list
          = link_to  "ログアウト", destroy_user_session_path, method: :delete
      - else
        %li.list
          = link_to  "新規登録", new_user_registration_path, method: :get
        %li.list
          = link_to  "ログイン", new_user_session_path, method: :get

app/views/blogs/create.html.haml
%p 投稿が完了しました
%a.btn{href: "/blogs"} 投稿一覧べ戻る

app/views/blogs/destroy.html.haml
.after
  .afterbox
    .afterstyle
      削除が完了しました
    .afterbtn
      = link_to "投稿一覧へ戻る", root_path

app/views/blogs/edit.html.haml
.formstyle
  .formbox
    =form_for [@blog] do |f|
      .field-label
        = f.text_field :image, placeholder: "Image Url", type: "text"
      .field-label
        = f.text_field :text, placeholder: "text", type: "text"
      .field-label
        = f.text_field :name, placeholder: "name", type: "text"
      .field-label
        = f.submit 'Edit', class: 'btn'

app/views/blogs/index.html.haml
= render partial: 'blogs/header'
= render partial: 'blogs/content', locals: { blogs: @blogs }

app/views/blogs/new.html.haml
.formstyle
  .formbox
    = form_for [@blog] do |f|
      .field-label__image
        = f.text_field :image, placeholder: "Image Url", type: "text"
      .field-label__text
        = f.text_field :text, placeholder: "文章を入力してください", type: "text"
      .field-label__name
        = f.text_field :name, placeholder: "ニックネームを入力してください", type: "text"
      .field-label__btn
        = f.submit 'Send', class: 'btn'

app/views/blogs/update.html.haml
.after
  .afterbox
    .afterstyle
      更新が完了しました
    .afterbtn
      = link_to "投稿一覧へ戻る", root_path

app/views/favorites/show.html.haml
.favorite
  %h2.favorite__title
    = link_to "Poemer", root_path
  .favoritepage
    .favoritepagecontent
      %h2.title <お気に入り一覧>
      - @blogs.each do |blog|
        .favoritepagecontents
          .favoritepage__poems
            .favoritepage__poems-text
              .favoritepage__poems-text-box
              - if blog.text.present?
                = blog.text
              .favoritepage__poems-image-box
              = image_tag blog.image
                - if blog.image.present?
              .favoritepage__poems-name-box
              = blog.name
              .favoritepage__poems-time-box
              = format_posted_time(blog.created_at)
    = paginate @blogs

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Miniblog
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    / / Compiled and minified CSS
    / %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css", :rel => "stylesheet"}/
    / Compiled and minified JavaScript
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=", :src => "https://code.jquery.com/jquery-3.3.1.js"}
    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/

  %body
    = yield

app/views/users/show.html.haml
= render partial: 'blogs/header'
.mypage
  .mypagecontent
    %h2.title <あなたの投稿一覧>
    - @blogs.each do |blog|
      .mypagecontents
        .mypage__poems
          .mypage__poems-text
            .mypage__poems-text-box
            - if blog.text.present?
              = blog.text
            .mypage__poems-image-box
            = image_tag blog.image
              - if blog.image.present?
            .mypage__poems-name-box
            = blog.name
            .mypage__poems-time-box
            = format_posted_time(blog.created_at)
  = paginate @blogs